spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jinn520/springcloudconfig.git
          search-paths: config
          default-label: master
          username: jinn520
          password:
server:
  port: 8888